/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    departments: Department;
    roles: Role;
    vendors: Vendor;
    'gl-accounts': GlAccount;
    dimensions: Dimension;
    'tax-codes': TaxCode;
    stages: Stage;
    sections: Section;
    fields: Field;
    documents: Document;
    batches: Batch;
    invoices: Invoice;
    'invoice-lines': InvoiceLine;
    'invoice-comments': InvoiceComment;
    'audit-events': AuditEvent;
    'approval-rules': ApprovalRule;
    'coding-restrictions': CodingRestriction;
    'email-templates': EmailTemplate;
    'email-triggers': EmailTrigger;
    'email-settings': EmailSetting;
    'coding-rules': CodingRule;
    'gl-format': GlFormat;
    'intake-settings': IntakeSetting;
    'duplicate-rules': DuplicateRule;
    'action-reasons': ActionReason;
    'saved-views': SavedView;
    'department-segment-map': DepartmentSegmentMap;
    'ocr-field-map': OcrFieldMap;
    'email-suppression': EmailSuppression;
    'intake-quarantine': IntakeQuarantine;
    'intake-events': IntakeEvent;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    'gl-accounts': GlAccountsSelect<false> | GlAccountsSelect<true>;
    dimensions: DimensionsSelect<false> | DimensionsSelect<true>;
    'tax-codes': TaxCodesSelect<false> | TaxCodesSelect<true>;
    stages: StagesSelect<false> | StagesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    fields: FieldsSelect<false> | FieldsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    batches: BatchesSelect<false> | BatchesSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'invoice-lines': InvoiceLinesSelect<false> | InvoiceLinesSelect<true>;
    'invoice-comments': InvoiceCommentsSelect<false> | InvoiceCommentsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'approval-rules': ApprovalRulesSelect<false> | ApprovalRulesSelect<true>;
    'coding-restrictions': CodingRestrictionsSelect<false> | CodingRestrictionsSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'email-triggers': EmailTriggersSelect<false> | EmailTriggersSelect<true>;
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    'coding-rules': CodingRulesSelect<false> | CodingRulesSelect<true>;
    'gl-format': GlFormatSelect<false> | GlFormatSelect<true>;
    'intake-settings': IntakeSettingsSelect<false> | IntakeSettingsSelect<true>;
    'duplicate-rules': DuplicateRulesSelect<false> | DuplicateRulesSelect<true>;
    'action-reasons': ActionReasonsSelect<false> | ActionReasonsSelect<true>;
    'saved-views': SavedViewsSelect<false> | SavedViewsSelect<true>;
    'department-segment-map': DepartmentSegmentMapSelect<false> | DepartmentSegmentMapSelect<true>;
    'ocr-field-map': OcrFieldMapSelect<false> | OcrFieldMapSelect<true>;
    'email-suppression': EmailSuppressionSelect<false> | EmailSuppressionSelect<true>;
    'intake-quarantine': IntakeQuarantineSelect<false> | IntakeQuarantineSelect<true>;
    'intake-events': IntakeEventsSelect<false> | IntakeEventsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: (number | null) | Role;
  department?: (number | null) | Department;
  avatar?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  description?: string | null;
  permissions?:
    | {
        action:
          | 'view'
          | 'edit'
          | 'assign'
          | 'code'
          | 'approve'
          | 'reject'
          | 'reassign'
          | 'post'
          | 'archive'
          | 'export'
          | 'delete'
          | 'configure'
          | 'verify';
        object: 'invoice' | 'document' | 'batch' | 'settings' | 'audit_log' | 'role';
        scope: 'own' | 'department' | 'all';
        stages?: (number | Stage)[] | null;
        id?: string | null;
      }[]
    | null;
  confidential?: boolean | null;
  bypassCodingRestrictions?: boolean | null;
  allowSelfReassign?: boolean | null;
  isSystem?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages".
 */
export interface Stage {
  id: number;
  systemId:
    | 'to_be_assigned'
    | 'to_be_coded'
    | 'conditional_approvals'
    | 'ap_review'
    | 'ready_for_processing'
    | 'processed'
    | 'treasurer_review'
    | 'completed';
  label: string;
  order: number;
  tone?: ('slate' | 'blue' | 'violet' | 'amber' | 'green' | 'red') | null;
  active?: boolean | null;
  required?: boolean | null;
  bulkAssign?: boolean | null;
  batchAssign?: boolean | null;
  verifyFlag?: boolean | null;
  allowReject?: boolean | null;
  allowReassign?: boolean | null;
  fieldsEditableBy?: (number | Role)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  code: string;
  head?: (number | null) | User;
  /**
   * Who approves invoices coded to this department's GL accounts. Leave blank to use the department head.
   */
  reviewer?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  vendorNumber: string;
  name: string;
  email?: string | null;
  phone?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  paymentTerms?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gl-accounts".
 */
export interface GlAccount {
  id: number;
  /**
   * Must match the GL account format set in Settings → Coding Restrictions.
   */
  code: string;
  description: string;
  active?: boolean | null;
  segments?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dimensions".
 */
export interface Dimension {
  id: number;
  kind: 'cost_center' | 'project' | 'fund' | 'job_code';
  code: string;
  description: string;
  label?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tax-codes".
 */
export interface TaxCode {
  id: number;
  code: string;
  label: string;
  /**
   * Decimal, e.g. 0.13 for 13%
   */
  rate: number;
  /**
   * Decimal, 0-1
   */
  recoverablePct: number;
  recoverableGl?: (number | null) | GlAccount;
  apControlGl?: (number | null) | GlAccount;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  name: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fields".
 */
export interface Field {
  id: number;
  /**
   * Stable id used in invoice.customFields and lines.customLineFields
   */
  fieldKey: string;
  label: string;
  scope: 'header' | 'line';
  section?: (number | null) | Section;
  order?: number | null;
  type:
    | 'text'
    | 'textarea'
    | 'richtext'
    | 'number'
    | 'currency'
    | 'date'
    | 'choice'
    | 'multiselect'
    | 'yesno'
    | 'lookup'
    | 'user'
    | 'group'
    | 'file';
  width?: ('full' | 'half' | 'third' | 'quarter') | null;
  options?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  lookupEntity?: ('vendors' | 'gl-accounts' | 'cost_center' | 'project' | 'fund' | 'job_code' | 'tax-codes') | null;
  mandatoryAtStages?: (number | Stage)[] | null;
  /**
   * Offer this field as a column on All Requests. The CSV export follows whatever columns the user has on screen, so there is no separate export setting.
   */
  showAsColumn?: boolean | null;
  exportable?: boolean | null;
  isSystem?: boolean | null;
  removable?: boolean | null;
  description?: string | null;
  placeholder?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  invoice?: (number | null) | Invoice;
  uploadedBy?: (number | null) | User;
  softDeleted?: boolean | null;
  deletedReason?: string | null;
  _key?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceNumber: string;
  vendor?: (number | null) | Vendor;
  invoiceDate?: string | null;
  dueDate?: string | null;
  fiscalYear?: string | null;
  poNumber?: string | null;
  subtotal?: number | null;
  totalTax?: number | null;
  grandTotal?: number | null;
  currentStage: number | Stage;
  departments?: (number | Department)[] | null;
  assignees?: (number | User)[] | null;
  /**
   * Per-recipient approval status at current stage
   */
  approvals?:
    | {
        user: number | User;
        stage: number | Stage;
        status?: ('pending' | 'approved' | 'rejected') | null;
        at?: string | null;
        comment?: string | null;
        id?: string | null;
      }[]
    | null;
  batch?: (number | null) | Batch;
  verified?: boolean | null;
  verifiedAt?: string | null;
  verifiedBy?: (number | null) | User;
  confidential?: boolean | null;
  flags?: {
    noAttachment?: boolean | null;
    ocrFailed?: boolean | null;
    vendorSetupRequired?: boolean | null;
    possibleDuplicate?: boolean | null;
    amountMismatch?: boolean | null;
    archiveFailed?: boolean | null;
    archiveAttempts?: number | null;
  };
  createdVia?: ('email' | 'manual') | null;
  /**
   * 0-1 vendor confidence score from OCR
   */
  ocrConfidence?: number | null;
  /**
   * Where an emailed invoice came from. Empty on invoices somebody typed in.
   */
  intake?: {
    sender?: string | null;
    subject?: string | null;
    receivedAt?: string | null;
    /**
     * Mailbox reference for the original email, so it can be opened again.
     */
    messageId?: string | null;
    /**
     * The message id the sending mail system stamped on the email.
     */
    internetMessageId?: string | null;
    attachmentName?: string | null;
  };
  /**
   * Keys of the header fields whose values were read off the scan rather than typed by a person. Drives the "read from the invoice" marker in the header tab.
   */
  ocrFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Header custom field values keyed by Field.fieldKey. Driven by Settings → Fields.
   */
  customFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  documents?: (number | Document)[] | null;
  softDeleted?: boolean | null;
  deletedReason?: string | null;
  archivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: number;
  number: string;
  createdBy?: (number | null) | User;
  closedAt?: string | null;
  closedBy?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-lines".
 */
export interface InvoiceLine {
  id: number;
  invoice: number | Invoice;
  order?: number | null;
  glAccount?: (number | null) | GlAccount;
  costCenter?: (number | null) | Dimension;
  project?: (number | null) | Dimension;
  fund?: (number | null) | Dimension;
  jobCode?: (number | null) | Dimension;
  amount?: number | null;
  taxCode?: (number | null) | TaxCode;
  taxAmount?: number | null;
  recoverable?: number | null;
  nonRecoverable?: number | null;
  description?: string | null;
  /**
   * Custom coding-line field values keyed by Field.fieldKey
   */
  customLineFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-comments".
 */
export interface InvoiceComment {
  id: number;
  invoice: number | Invoice;
  author: number | User;
  body: string;
  mentions?: (number | User)[] | null;
  preview?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  invoice?: (number | null) | Invoice;
  actor?: (number | null) | User;
  action:
    | 'created'
    | 'updated'
    | 'assigned'
    | 'reassigned'
    | 'approved'
    | 'rejected'
    | 'coded'
    | 'amounts_corrected'
    | 'batch_applied'
    | 'batch_wiped'
    | 'batch_closed'
    | 'exported'
    | 'archived'
    | 'archive_failed'
    | 'archive_retry'
    | 'verified'
    | 'unverified'
    | 'document_uploaded'
    | 'document_deleted'
    | 'comment_added'
    | 'soft_deleted'
    | 'restored'
    | 'flag_set'
    | 'flag_cleared';
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approval-rules".
 */
export interface ApprovalRule {
  id: number;
  name: string;
  order?: number | null;
  enabled?: boolean | null;
  /**
   * ConditionGroup { operator: "and"|"or", conditions: [{ fieldKey, operator, value }] }
   */
  conditions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approvers?:
    | {
        type: 'user' | 'role' | 'department_head';
        user?: (number | null) | User;
        role?: (number | null) | Role;
        department?: (number | null) | Department;
        id?: string | null;
      }[]
    | null;
  mode?: ('parallel' | 'sequential') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Retired. Coding restrictions are configured under Settings → Coding Restrictions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coding-restrictions".
 */
export interface CodingRestriction {
  id: number;
  department: number | Department;
  rules?:
    | {
        /**
         * 1-based segment number in the GL code
         */
        segmentIndex: number;
        operator: 'equals' | 'starts_with' | 'in';
        value?: string | null;
        listValues?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  departmentLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  name: string;
  subject: string;
  bodyHtml: string;
  enabled?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-triggers".
 */
export interface EmailTrigger {
  id: number;
  name: string;
  event:
    | 'submission'
    | 'approval'
    | 'rejection'
    | 'reassignment'
    | 'conditional_routing'
    | 'treasurer_routing'
    | 'batch_applied'
    | 'archive_failed';
  stage?: (number | null) | Stage;
  template: number | EmailTemplate;
  recipients?:
    | {
        type: 'dynamic' | 'role' | 'user' | 'email';
        dynamicKey?: ('assignee' | 'approver' | 'rejecter' | 'submitter' | 'ap_supervisor') | null;
        role?: (number | null) | Role;
        user?: (number | null) | User;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  cc?:
    | {
        type: 'dynamic' | 'role' | 'user' | 'email';
        dynamicKey?: string | null;
        role?: (number | null) | Role;
        user?: (number | null) | User;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sender identity and the header/footer wrapped around every email body.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Display name recipients see in their inbox.
   */
  fromName: string;
  fromEmail: string;
  /**
   * Where replies go. Leave blank to use the From address.
   */
  replyTo?: string | null;
  /**
   * HTML placed above every template body. May contain placeholders from the token registry.
   */
  headerHtml: string;
  /**
   * HTML placed below every template body. May contain placeholders from the token registry.
   */
  footerHtml: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coding-rules".
 */
export interface CodingRule {
  id: number;
  /**
   * Header amount the coding lines must add up to.
   */
  matchTarget: 'subtotal' | 'grandTotal' | 'disabled';
  /**
   * What happens when an invoice is not fully coded.
   */
  onMismatch: 'block' | 'warn' | 'disabled';
  /**
   * Shown to the user when an approval is blocked or warned.
   */
  message: string;
  /**
   * Rounding allowance in dollars, e.g. 0.01 for one cent.
   */
  tolerance: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * One row only. Edit it from Settings → Coding Restrictions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gl-format".
 */
export interface GlFormat {
  id: number;
  /**
   * One X for each character of the code, with the separator between the parts. Parts may be different lengths, for example XX-XXX-XXXX-XXXXX.
   */
  mask: string;
  /**
   * What each part of the code is called, left to right.
   */
  segmentLabels?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Which part of the code names the sub-department, counting from the left. The first part is 1.
   */
  departmentSegment: number;
  /**
   * Where sub-departments that no range covers are sent. New capital-project codes land here so Finance can see them and map them.
   */
  catchAllDepartment: number | Department;
  updatedAt: string;
  createdAt: string;
}
/**
 * The mailbox invoices are emailed to, and who may email it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-settings".
 */
export interface IntakeSetting {
  id: number;
  /**
   * When off, nothing arriving in the mailbox is turned into an invoice.
   */
  enabled?: boolean | null;
  /**
   * The shared mailbox invoices are forwarded to, e.g. ap@aurora.ca.
   */
  mailboxAddress?: string | null;
  senderPolicy: 'internal_only' | 'public';
  /**
   * Email domains counted as staff, e.g. aurora.ca. Subdomains of a listed domain also count.
   */
  internalDomains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How sure the reading has to be before a value is filled in. Below this the field is left blank. 0.8 means 80%.
   */
  confidenceThreshold: number;
  /**
   * How far the amounts on an invoice may disagree before it is flagged for review, in dollars.
   */
  amountTolerance: number;
  /**
   * Set automatically when the mailbox connection is started.
   */
  subscriptionId?: string | null;
  /**
   * The mailbox connection is renewed automatically before this time.
   */
  subscriptionExpiresAt?: string | null;
  /**
   * Last time the mailbox told us something had arrived.
   */
  lastNotificationAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What counts as the same invoice arriving twice, and what happens then.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duplicate-rules".
 */
export interface DuplicateRule {
  id: number;
  /**
   * Fields that together identify an invoice. Default is vendor plus invoice number.
   */
  keyFields: {
    field:
      | 'invoiceNumber'
      | 'vendorName'
      | 'grandTotal'
      | 'poNumber'
      | 'subtotal'
      | 'totalTax'
      | 'invoiceDate'
      | 'dueDate'
      | 'fiscalYear';
    id?: string | null;
  }[];
  action: 'flag' | 'block' | 'allow';
  /**
   * Do not compare against invoices that were cancelled.
   */
  ignoreCancelled?: boolean | null;
  /**
   * Treat differences in capitals and spacing as the same text.
   */
  caseInsensitive?: boolean | null;
  /**
   * Also check invoices somebody types in, not only emailed ones.
   */
  appliesToManualEntry?: boolean | null;
  /**
   * Only compare against invoices from the last N days. Leave blank to compare against all of them.
   */
  windowDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reason dropdowns shown when an invoice is reassigned, rejected or cancelled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "action-reasons".
 */
export interface ActionReason {
  id: number;
  /**
   * Which action this row belongs to.
   */
  scope: 'reassign' | 'reject' | 'cancel';
  kind: 'reason' | 'policy';
  /**
   * What the clerk reads in the dropdown. Required on a reason option.
   */
  label?: string | null;
  order?: number | null;
  active?: boolean | null;
  /**
   * The built-in Other option. Reveals a free-text line and cannot be deleted.
   */
  isOther?: boolean | null;
  /**
   * Whether a reason must be given before this action can be completed.
   */
  reasonRequired?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-views".
 */
export interface SavedView {
  id: number;
  name: string;
  /**
   * The person the view belongs to. Never changes, including for published views.
   */
  owner: number | User;
  /**
   * Stage systemId the view applies to, or 'all'.
   */
  stage: string;
  /**
   * Visible column ids, in display order.
   */
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Full column order including hidden columns.
   */
  columnOrder?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * ColumnFilterSpec[] — AND across columns, OR within a column.
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * [{ id, desc }] in priority order.
   */
  sort?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Opens automatically for the owner. At most one per owner.
   */
  isDefault?: boolean | null;
  /**
   * Roles that may open this view read-only. Set by an administrator.
   */
  publishedToRoles?: (number | Role)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maintained from Settings → Coding Restrictions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "department-segment-map".
 */
export interface DepartmentSegmentMap {
  id: number;
  /**
   * Who codes and approves invoices against these sub-departments.
   */
  department: number | Department;
  /**
   * First sub-department number in the range, written exactly as it appears in the GL code (for example 0400).
   */
  fromValue: string;
  /**
   * Last sub-department number in the range. Leave blank when the row covers a single sub-department — a single value always beats a range that contains it.
   */
  toValue?: string | null;
  /**
   * Optional reminder of what this covers, for example "Swim Program".
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Which reading from a scanned invoice fills which field in this app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ocr-field-map".
 */
export interface OcrFieldMap {
  id: number;
  /**
   * Key of the field in this app that the value lands in.
   */
  appField: string;
  sourceField:
    | 'InvoiceId'
    | 'VendorName'
    | 'VendorAddress'
    | 'VendorTaxId'
    | 'CustomerName'
    | 'CustomerId'
    | 'InvoiceDate'
    | 'DueDate'
    | 'PurchaseOrder'
    | 'SubTotal'
    | 'TotalTax'
    | 'InvoiceTotal'
    | 'AmountDue'
    | 'PreviousUnpaidBalance'
    | 'ServiceStartDate'
    | 'ServiceEndDate'
    | 'PaymentTerm';
  enabled?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People and groups who should not get an automatic reply when they email an invoice in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-suppression".
 */
export interface EmailSuppression {
  id: number;
  /**
   * An email address, a whole domain, or the name of a directory group.
   */
  value: string;
  kind: 'address' | 'domain' | 'group';
  /**
   * Why this one is on the list.
   */
  note?: string | null;
  addedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Emails the mailbox turned away, waiting for someone to look at them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-quarantine".
 */
export interface IntakeQuarantine {
  id: number;
  sender: string;
  subject?: string | null;
  receivedAt: string;
  reason: 'external_sender' | 'unreadable_sender' | 'no_internal_domains_configured';
  /**
   * Mailbox reference for the original message, used to fetch it again on release.
   */
  messageId: string;
  internetMessageId?: string | null;
  attachmentCount?: number | null;
  released?: boolean | null;
  releasedAt?: string | null;
  releasedBy?: (number | null) | User;
  /**
   * Why the last attempt to release this message did not work.
   */
  releaseError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What arrived by email, and what was read off it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-events".
 */
export interface IntakeEvent {
  id: number;
  /**
   * Identifies one message and one file within it, so a repeated delivery is not processed twice.
   */
  messageKey: string;
  messageId: string;
  internetMessageId?: string | null;
  sender?: string | null;
  subject?: string | null;
  receivedAt: string;
  status: 'created' | 'quarantined' | 'blocked_duplicate' | 'skipped' | 'failed';
  invoice?: (number | null) | Invoice;
  attachmentName?: string | null;
  ocrStatus?: ('extracted' | 'failed' | 'skipped') | null;
  /**
   * Exactly what the reading produced, before anyone edited it.
   */
  extraction?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The values that were actually put on the invoice.
   */
  appliedValues?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The setting in force when this invoice was read.
   */
  confidenceThreshold?: number | null;
  /**
   * Plain-language explanation of why this one did not go through.
   */
  failureReason?: string | null;
  /**
   * The confirmation reply composed for the sender. Empty when the sender is on the suppression list.
   */
  receipt?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'gl-accounts';
        value: number | GlAccount;
      } | null)
    | ({
        relationTo: 'dimensions';
        value: number | Dimension;
      } | null)
    | ({
        relationTo: 'tax-codes';
        value: number | TaxCode;
      } | null)
    | ({
        relationTo: 'stages';
        value: number | Stage;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'fields';
        value: number | Field;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'batches';
        value: number | Batch;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'invoice-lines';
        value: number | InvoiceLine;
      } | null)
    | ({
        relationTo: 'invoice-comments';
        value: number | InvoiceComment;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'approval-rules';
        value: number | ApprovalRule;
      } | null)
    | ({
        relationTo: 'coding-restrictions';
        value: number | CodingRestriction;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'email-triggers';
        value: number | EmailTrigger;
      } | null)
    | ({
        relationTo: 'email-settings';
        value: number | EmailSetting;
      } | null)
    | ({
        relationTo: 'coding-rules';
        value: number | CodingRule;
      } | null)
    | ({
        relationTo: 'gl-format';
        value: number | GlFormat;
      } | null)
    | ({
        relationTo: 'intake-settings';
        value: number | IntakeSetting;
      } | null)
    | ({
        relationTo: 'duplicate-rules';
        value: number | DuplicateRule;
      } | null)
    | ({
        relationTo: 'action-reasons';
        value: number | ActionReason;
      } | null)
    | ({
        relationTo: 'saved-views';
        value: number | SavedView;
      } | null)
    | ({
        relationTo: 'department-segment-map';
        value: number | DepartmentSegmentMap;
      } | null)
    | ({
        relationTo: 'ocr-field-map';
        value: number | OcrFieldMap;
      } | null)
    | ({
        relationTo: 'email-suppression';
        value: number | EmailSuppression;
      } | null)
    | ({
        relationTo: 'intake-quarantine';
        value: number | IntakeQuarantine;
      } | null)
    | ({
        relationTo: 'intake-events';
        value: number | IntakeEvent;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  department?: T;
  avatar?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  head?: T;
  reviewer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  permissions?:
    | T
    | {
        action?: T;
        object?: T;
        scope?: T;
        stages?: T;
        id?: T;
      };
  confidential?: T;
  bypassCodingRestrictions?: T;
  allowSelfReassign?: T;
  isSystem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  vendorNumber?: T;
  name?: T;
  email?: T;
  phone?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  paymentTerms?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gl-accounts_select".
 */
export interface GlAccountsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  active?: T;
  segments?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dimensions_select".
 */
export interface DimensionsSelect<T extends boolean = true> {
  kind?: T;
  code?: T;
  description?: T;
  label?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tax-codes_select".
 */
export interface TaxCodesSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  rate?: T;
  recoverablePct?: T;
  recoverableGl?: T;
  apControlGl?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages_select".
 */
export interface StagesSelect<T extends boolean = true> {
  systemId?: T;
  label?: T;
  order?: T;
  tone?: T;
  active?: T;
  required?: T;
  bulkAssign?: T;
  batchAssign?: T;
  verifyFlag?: T;
  allowReject?: T;
  allowReassign?: T;
  fieldsEditableBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fields_select".
 */
export interface FieldsSelect<T extends boolean = true> {
  fieldKey?: T;
  label?: T;
  scope?: T;
  section?: T;
  order?: T;
  type?: T;
  width?: T;
  options?:
    | T
    | {
        value?: T;
        id?: T;
      };
  lookupEntity?: T;
  mandatoryAtStages?: T;
  showAsColumn?: T;
  exportable?: T;
  isSystem?: T;
  removable?: T;
  description?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  invoice?: T;
  uploadedBy?: T;
  softDeleted?: T;
  deletedReason?: T;
  _key?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  number?: T;
  createdBy?: T;
  closedAt?: T;
  closedBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  vendor?: T;
  invoiceDate?: T;
  dueDate?: T;
  fiscalYear?: T;
  poNumber?: T;
  subtotal?: T;
  totalTax?: T;
  grandTotal?: T;
  currentStage?: T;
  departments?: T;
  assignees?: T;
  approvals?:
    | T
    | {
        user?: T;
        stage?: T;
        status?: T;
        at?: T;
        comment?: T;
        id?: T;
      };
  batch?: T;
  verified?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  confidential?: T;
  flags?:
    | T
    | {
        noAttachment?: T;
        ocrFailed?: T;
        vendorSetupRequired?: T;
        possibleDuplicate?: T;
        amountMismatch?: T;
        archiveFailed?: T;
        archiveAttempts?: T;
      };
  createdVia?: T;
  ocrConfidence?: T;
  intake?:
    | T
    | {
        sender?: T;
        subject?: T;
        receivedAt?: T;
        messageId?: T;
        internetMessageId?: T;
        attachmentName?: T;
      };
  ocrFields?: T;
  customFields?: T;
  documents?: T;
  softDeleted?: T;
  deletedReason?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-lines_select".
 */
export interface InvoiceLinesSelect<T extends boolean = true> {
  invoice?: T;
  order?: T;
  glAccount?: T;
  costCenter?: T;
  project?: T;
  fund?: T;
  jobCode?: T;
  amount?: T;
  taxCode?: T;
  taxAmount?: T;
  recoverable?: T;
  nonRecoverable?: T;
  description?: T;
  customLineFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-comments_select".
 */
export interface InvoiceCommentsSelect<T extends boolean = true> {
  invoice?: T;
  author?: T;
  body?: T;
  mentions?: T;
  preview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  invoice?: T;
  actor?: T;
  action?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approval-rules_select".
 */
export interface ApprovalRulesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  enabled?: T;
  conditions?: T;
  approvers?:
    | T
    | {
        type?: T;
        user?: T;
        role?: T;
        department?: T;
        id?: T;
      };
  mode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coding-restrictions_select".
 */
export interface CodingRestrictionsSelect<T extends boolean = true> {
  department?: T;
  rules?:
    | T
    | {
        segmentIndex?: T;
        operator?: T;
        value?: T;
        listValues?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  departmentLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  bodyHtml?: T;
  enabled?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-triggers_select".
 */
export interface EmailTriggersSelect<T extends boolean = true> {
  name?: T;
  event?: T;
  stage?: T;
  template?: T;
  recipients?:
    | T
    | {
        type?: T;
        dynamicKey?: T;
        role?: T;
        user?: T;
        email?: T;
        id?: T;
      };
  cc?:
    | T
    | {
        type?: T;
        dynamicKey?: T;
        role?: T;
        user?: T;
        email?: T;
        id?: T;
      };
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  fromName?: T;
  fromEmail?: T;
  replyTo?: T;
  headerHtml?: T;
  footerHtml?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coding-rules_select".
 */
export interface CodingRulesSelect<T extends boolean = true> {
  matchTarget?: T;
  onMismatch?: T;
  message?: T;
  tolerance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gl-format_select".
 */
export interface GlFormatSelect<T extends boolean = true> {
  mask?: T;
  segmentLabels?:
    | T
    | {
        label?: T;
        id?: T;
      };
  departmentSegment?: T;
  catchAllDepartment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-settings_select".
 */
export interface IntakeSettingsSelect<T extends boolean = true> {
  enabled?: T;
  mailboxAddress?: T;
  senderPolicy?: T;
  internalDomains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  confidenceThreshold?: T;
  amountTolerance?: T;
  subscriptionId?: T;
  subscriptionExpiresAt?: T;
  lastNotificationAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duplicate-rules_select".
 */
export interface DuplicateRulesSelect<T extends boolean = true> {
  keyFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  action?: T;
  ignoreCancelled?: T;
  caseInsensitive?: T;
  appliesToManualEntry?: T;
  windowDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "action-reasons_select".
 */
export interface ActionReasonsSelect<T extends boolean = true> {
  scope?: T;
  kind?: T;
  label?: T;
  order?: T;
  active?: T;
  isOther?: T;
  reasonRequired?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-views_select".
 */
export interface SavedViewsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  stage?: T;
  columns?: T;
  columnOrder?: T;
  filters?: T;
  sort?: T;
  isDefault?: T;
  publishedToRoles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "department-segment-map_select".
 */
export interface DepartmentSegmentMapSelect<T extends boolean = true> {
  department?: T;
  fromValue?: T;
  toValue?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ocr-field-map_select".
 */
export interface OcrFieldMapSelect<T extends boolean = true> {
  appField?: T;
  sourceField?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-suppression_select".
 */
export interface EmailSuppressionSelect<T extends boolean = true> {
  value?: T;
  kind?: T;
  note?: T;
  addedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-quarantine_select".
 */
export interface IntakeQuarantineSelect<T extends boolean = true> {
  sender?: T;
  subject?: T;
  receivedAt?: T;
  reason?: T;
  messageId?: T;
  internetMessageId?: T;
  attachmentCount?: T;
  released?: T;
  releasedAt?: T;
  releasedBy?: T;
  releaseError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-events_select".
 */
export interface IntakeEventsSelect<T extends boolean = true> {
  messageKey?: T;
  messageId?: T;
  internetMessageId?: T;
  sender?: T;
  subject?: T;
  receivedAt?: T;
  status?: T;
  invoice?: T;
  attachmentName?: T;
  ocrStatus?: T;
  extraction?: T;
  appliedValues?: T;
  confidenceThreshold?: T;
  failureReason?: T;
  receipt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}